/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.frame;

import javax.swing.JMenuItem;

/**
 *
 * @author jeca
 */
public class JFrameUser extends javax.swing.JFrame {

    /**
     * Creates new form JFrameUser
     */
    public JFrameUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuReservation = new javax.swing.JMenu();
        jMenuItemReservationCreate = new javax.swing.JMenuItem();
        jMenuItemReservationCancel = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemAccountLogout = new javax.swing.JMenuItem();
        jMenuItemAccountDeactivate = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuReservation.setText("Rezervacija");

        jMenuItemReservationCreate.setText("Kreiraj");
        jMenuReservation.add(jMenuItemReservationCreate);

        jMenuItemReservationCancel.setText("Otkazi");
        jMenuReservation.add(jMenuItemReservationCancel);

        jMenuBar.add(jMenuReservation);

        jMenuAccount.setText("Nalog");

        jMenuItemAccountLogout.setText("Odjava");
        jMenuAccount.add(jMenuItemAccountLogout);

        jMenuItemAccountDeactivate.setText("Deaktivacija");
        jMenuAccount.add(jMenuItemAccountDeactivate);

        jMenuBar.add(jMenuAccount);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAccountDeactivate;
    private javax.swing.JMenuItem jMenuItemAccountLogout;
    private javax.swing.JMenuItem jMenuItemReservationCancel;
    private javax.swing.JMenuItem jMenuItemReservationCreate;
    private javax.swing.JMenu jMenuReservation;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getjMenuItemAccountDeactivate() {
        return jMenuItemAccountDeactivate;
    }

    public JMenuItem getjMenuItemAccountLogout() {
        return jMenuItemAccountLogout;
    }

    public JMenuItem getjMenuItemReservationCancel() {
        return jMenuItemReservationCancel;
    }

    public JMenuItem getjMenuItemReservationCreate() {
        return jMenuItemReservationCreate;
    }
}