/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.frame;

import domain.Restaurant;
import exception.CommunicationException;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.controller.ControllerMenuAccount;
import ui.coordinator.GUICoordinator;
import ui.view.panel.JPanelReservation;
import ui.view.panel.JPanelRestaurant;
import ui.view.panel.JPanelRestaurantSearch;
import util.FormMode;

/**
 *
 * @author jeca
 */
public class JFrameUser extends javax.swing.JFrame {

    /**
     * Creates new form JFrameUser
     */
    public JFrameUser() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuReservation = new javax.swing.JMenu();
        jMenuItemReservationCreate = new javax.swing.JMenuItem();
        jMenuItemReservationCancel = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemAccountLogout = new javax.swing.JMenuItem();
        jMenuItemAccountDeactivate = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuReservation.setText("Rezervacija");

        jMenuItemReservationCreate.setText("Kreiraj");
        jMenuItemReservationCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservationCreateActionPerformed(evt);
            }
        });
        jMenuReservation.add(jMenuItemReservationCreate);

        jMenuItemReservationCancel.setText("Otkazi");
        jMenuReservation.add(jMenuItemReservationCancel);

        jMenuBar.add(jMenuReservation);

        jMenuAccount.setText("Nalog");

        jMenuItemAccountLogout.setText("Odjava");
        jMenuItemAccountLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAccountLogoutActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemAccountLogout);

        jMenuItemAccountDeactivate.setText("Deaktivacija");
        jMenuItemAccountDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAccountDeactivateActionPerformed(evt);
            }
        });
        jMenuAccount.add(jMenuItemAccountDeactivate);

        jMenuBar.add(jMenuAccount);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAccountLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAccountLogoutActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da se odjavite?", "Odjavljivanje", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
            try {
                ControllerMenuAccount.getInstance().logout();
                GUICoordinator.getInstance().logout(this);
            } catch (CommunicationException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItemAccountLogoutActionPerformed

    private void jMenuItemAccountDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAccountDeactivateActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da deaktivirate svoj nalog?", "Deaktivacija naloga", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
            try {
                ControllerMenuAccount.getInstance().deactivateAccount();
                GUICoordinator.getInstance().logout(this);
            } catch (CommunicationException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItemAccountDeactivateActionPerformed

    private void jMenuItemReservationCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservationCreateActionPerformed
        setCentralPanel(new JPanelRestaurantSearch(true));
    }//GEN-LAST:event_jMenuItemReservationCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAccountDeactivate;
    private javax.swing.JMenuItem jMenuItemAccountLogout;
    private javax.swing.JMenuItem jMenuItemReservationCancel;
    private javax.swing.JMenuItem jMenuItemReservationCreate;
    private javax.swing.JMenu jMenuReservation;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        this.setSize(1000, 800);
        this.setLocationRelativeTo(null);
    }
    
    private void setCentralPanel(JPanel panel) {
        this.getContentPane().removeAll();
        this.getContentPane().add(panel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }
}
