/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.frame;

import javax.swing.JMenuItem;

/**
 *
 * @author jeca
 */
public class JFrameMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameFirst
     */
    public JFrameMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jmiUserLogin = new javax.swing.JMenuItem();
        jmiUserRegistration = new javax.swing.JMenuItem();
        jMenuRestaurant = new javax.swing.JMenu();
        jmiRestaurantSearch = new javax.swing.JMenuItem();
        jMenuConfiguration = new javax.swing.JMenu();
        jMenuItemConfigServer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuUser.setText("Korisnik");

        jmiUserLogin.setText("Prijava");
        jMenuUser.add(jmiUserLogin);

        jmiUserRegistration.setText("Registracija");
        jMenuUser.add(jmiUserRegistration);

        jMenuBar.add(jMenuUser);

        jMenuRestaurant.setText("Restoran");

        jmiRestaurantSearch.setText("Pretraga");
        jMenuRestaurant.add(jmiRestaurantSearch);

        jMenuBar.add(jMenuRestaurant);

        jMenuConfiguration.setText("Konfiguracija");

        jMenuItemConfigServer.setText("Server");
        jMenuConfiguration.add(jMenuItemConfigServer);

        jMenuBar.add(jMenuConfiguration);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JMenuItem jMenuItemConfigServer;
    private javax.swing.JMenu jMenuRestaurant;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JMenuItem jmiRestaurantSearch;
    private javax.swing.JMenuItem jmiUserLogin;
    private javax.swing.JMenuItem jmiUserRegistration;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getJMenuItemRestaurantSearch() {
        return jmiRestaurantSearch;
    }

    public JMenuItem getJMenuItemUserLogin() {
        return jmiUserLogin;
    }

    public JMenuItem getJMenuItemRegistration() {
        return jmiUserRegistration;
    }

    public JMenuItem getjMenuItemConfigServer() {
        return jMenuItemConfigServer;
    } 
}
