/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.frame;

import javax.swing.JMenuItem;

/**
 *
 * @author jeca
 */
public class JFrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRestaurant
     */
    public JFrameAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuRestaurant = new javax.swing.JMenu();
        jMenuItemNewRestaurant = new javax.swing.JMenuItem();
        jMenuItemSearchRestaurants = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuConfiguration = new javax.swing.JMenu();
        jMenuItemConfigServer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuRestaurant.setText("Restoran");

        jMenuItemNewRestaurant.setText("Novi restoran");
        jMenuRestaurant.add(jMenuItemNewRestaurant);

        jMenuItemSearchRestaurants.setText("Pretraga restorana");
        jMenuRestaurant.add(jMenuItemSearchRestaurants);

        jMenuBar.add(jMenuRestaurant);

        jMenuAccount.setText("Nalog");

        jMenuItemLogout.setText("Odjava");
        jMenuAccount.add(jMenuItemLogout);

        jMenuBar.add(jMenuAccount);

        jMenuConfiguration.setText("Konfiguracija");

        jMenuItemConfigServer.setText("Server");
        jMenuConfiguration.add(jMenuItemConfigServer);

        jMenuBar.add(jMenuConfiguration);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConfiguration;
    private javax.swing.JMenuItem jMenuItemConfigServer;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemNewRestaurant;
    private javax.swing.JMenuItem jMenuItemSearchRestaurants;
    private javax.swing.JMenu jMenuRestaurant;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getjMenuItemLogout() {
        return jMenuItemLogout;
    }

    public JMenuItem getjMenuItemNewRestaurant() {
        return jMenuItemNewRestaurant;
    }

    public JMenuItem getjMenuItemSearchRestaurants() {
        return jMenuItemSearchRestaurants;
    }
    
    public JMenuItem getjMenuItemConfigServer() {
        return jMenuItemConfigServer;
    } 
}
