/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

/**
 *
 * @author jeca
 */
public class JFrameUser extends javax.swing.JFrame {

    /**
     * Creates new form JFrameUser
     */
    public JFrameUser() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuRestaurant = new javax.swing.JMenu();
        jMenuItemRestaurantSearch = new javax.swing.JMenuItem();
        jMenuBarRestaurantReservation = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jMenuItemAccountLogout = new javax.swing.JMenuItem();
        jMenuItemAccountDeactivate = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuRestaurant.setText("Restoran");

        jMenuItemRestaurantSearch.setText("Pretraga");
        jMenuRestaurant.add(jMenuItemRestaurantSearch);

        jMenuBarRestaurantReservation.setText("Rezervacija");
        jMenuRestaurant.add(jMenuBarRestaurantReservation);

        jMenuBar.add(jMenuRestaurant);

        jMenuAccount.setText("Nalog");

        jMenuItemAccountLogout.setText("Odjava");
        jMenuAccount.add(jMenuItemAccountLogout);

        jMenuItemAccountDeactivate.setText("Deaktivacija");
        jMenuAccount.add(jMenuItemAccountDeactivate);

        jMenuBar.add(jMenuAccount);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuBarRestaurantReservation;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAccountDeactivate;
    private javax.swing.JMenuItem jMenuItemAccountLogout;
    private javax.swing.JMenuItem jMenuItemRestaurantSearch;
    private javax.swing.JMenu jMenuRestaurant;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        this.setSize(1000, 800);
        this.setLocationRelativeTo(null);
    }
}
