/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import ui.view.panel.JPanelLogin;
import ui.view.panel.JPanelRegistration;
import ui.view.panel.JPanelRestaurantSearch;

/**
 *
 * @author jeca
 */
public class JFrameFirst extends javax.swing.JFrame {

    /**
     * Creates new form JFrameFirst
     */
    public JFrameFirst() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiUserLogin = new javax.swing.JMenuItem();
        jmiUserRegistration = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiRestaurantSearch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Korisnik");

        jmiUserLogin.setText("Prijava");
        jmiUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUserLoginActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUserLogin);

        jmiUserRegistration.setText("Registracija");
        jmiUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUserRegistrationActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUserRegistration);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Restoran");

        jmiRestaurantSearch.setText("Pretraga");
        jmiRestaurantSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRestaurantSearchActionPerformed(evt);
            }
        });
        jMenu2.add(jmiRestaurantSearch);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUserLoginActionPerformed
        JPanel panelLogin = new JPanelLogin();
        setCentralPanel(panelLogin);
    }//GEN-LAST:event_jmiUserLoginActionPerformed

    private void jmiUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUserRegistrationActionPerformed
        JPanel panelRegistration = new JPanelRegistration();
        setCentralPanel(panelRegistration);
    }//GEN-LAST:event_jmiUserRegistrationActionPerformed

    private void jmiRestaurantSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRestaurantSearchActionPerformed
        this.setCentralPanel(new JPanelRestaurantSearch());
    }//GEN-LAST:event_jmiRestaurantSearchActionPerformed

    private void setCentralPanel(JPanel panelRegistration) {
        this.getContentPane().removeAll();
        this.getContentPane().add(panelRegistration, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiRestaurantSearch;
    private javax.swing.JMenuItem jmiUserLogin;
    private javax.swing.JMenuItem jmiUserRegistration;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        this.setSize(600, 400);
        this.setLocationRelativeTo(null);

    }
}
