/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

import ui.view.panel.JPanelRestaurantNew;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author jeca
 */
public class JFrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRestaurant
     */
    public JFrameAdmin() {
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiNewRestaurant = new javax.swing.JMenuItem();
        jmiSearchRestaurants = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Restoran");

        jmiNewRestaurant.setText("Novi restoran");
        jmiNewRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewRestaurantActionPerformed(evt);
            }
        });
        jMenu1.add(jmiNewRestaurant);

        jmiSearchRestaurants.setText("Pretraga restorana");
        jMenu1.add(jmiSearchRestaurants);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNewRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewRestaurantActionPerformed
        JPanel newRestaurantPanel = new JPanelRestaurantNew();
        this.getContentPane().removeAll();
        this.getContentPane().add(newRestaurantPanel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jmiNewRestaurantActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiNewRestaurant;
    private javax.swing.JMenuItem jmiSearchRestaurants;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        this.setSize(1000, 800);
        this.setLocationRelativeTo(null);

    }
}
