/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.panel;

import domain.DiningTable;
import domain.Restaurant;
import exception.ValidationException;
import java.util.LinkedList;
import java.util.List;
import util.Cuisine;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ui.view.controller.panel.ControllerPanelRestaurantNew;
import ui.coordinator.GUICoordinator;
import ui.view.components.table.TableModelDiningTables;
import util.FieldLabelPair;
import util.FormMode;
import util.TablePosition;

/**
 *
 * @author jeca
 */
public class JPanelRestaurant extends javax.swing.JPanel {

    ControllerPanelRestaurantNew controller;
    List<FieldLabelPair> fieldLabelPairs;
    FormMode mode;

    /**
     * Creates new form JPanelNewRestaurant
     */
    public JPanelRestaurant(FormMode mode) {
        this.controller = ControllerPanelRestaurantNew.getInstance();
        initComponents();
        prepareForm(mode);
        initializeFieldLabelPairs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jcboxNonSmoking = new javax.swing.JCheckBox();
        jcboxPetsAllowed = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jcboxCuisine = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jtxtTIN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtAdress = new javax.swing.JTextField();
        jbtnSave = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jlblErrorName = new javax.swing.JLabel();
        jlblErrorTIN = new javax.swing.JLabel();
        jlblErrorAdress = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNumberOfPeople = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcboxPosition = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDiningTables = new javax.swing.JTable();
        jbtnAddDiningTable = new javax.swing.JButton();
        jlblErrorNumOfPeople = new javax.swing.JLabel();
        jbtnRemoveDiningTable = new javax.swing.JButton();
        jbtnUpdateDinningTable = new javax.swing.JButton();
        jtxtTableLabel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlblErrorTableLabel = new javax.swing.JLabel();
        jbtnChangeRestaurant = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Novi Restoran"));

        jLabel8.setText("Naziv restorana:");

        jcboxNonSmoking.setText("Nepušački");

        jcboxPetsAllowed.setText("Dozvoljeni ljubimci");

        jLabel9.setText("Vrsta kuhinje:");

        jLabel10.setText("PIB restorana:");

        jLabel11.setText("Adresa restorana:");

        jbtnSave.setText("Sačuvaj");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Otkaži");

        jlblErrorName.setForeground(new java.awt.Color(255, 0, 0));

        jlblErrorTIN.setForeground(new java.awt.Color(255, 0, 0));

        jlblErrorAdress.setForeground(new java.awt.Color(255, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Stolovi"));

        jLabel1.setText("Broj osoba:");

        jLabel2.setText("Pozicija:");

        jTableDiningTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDiningTables);

        jbtnAddDiningTable.setText("Dodaj sto");
        jbtnAddDiningTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddDiningTableActionPerformed(evt);
            }
        });

        jlblErrorNumOfPeople.setForeground(new java.awt.Color(255, 0, 0));

        jbtnRemoveDiningTable.setText("Obriši sto");
        jbtnRemoveDiningTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveDiningTableActionPerformed(evt);
            }
        });

        jbtnUpdateDinningTable.setText("Izmeni sto");
        jbtnUpdateDinningTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateDinningTableActionPerformed(evt);
            }
        });

        jLabel3.setText("Oznaka stola:");

        jlblErrorTableLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlblErrorTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtNumberOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcboxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jlblErrorNumOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jtxtTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(81, 81, 81))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnUpdateDinningTable)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnRemoveDiningTable))
                            .addComponent(jbtnAddDiningTable))))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNumberOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcboxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblErrorNumOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblErrorTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAddDiningTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRemoveDiningTable)
                    .addComponent(jbtnUpdateDinningTable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnChangeRestaurant.setText("Izmeni");
        jbtnChangeRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangeRestaurantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(24, 24, 24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jlblErrorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlblErrorAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblErrorTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcboxNonSmoking)
                                    .addComponent(jcboxPetsAllowed)
                                    .addComponent(jcboxCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnChangeRestaurant)
                        .addGap(40, 40, 40)
                        .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcboxNonSmoking))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtTIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcboxCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblErrorTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcboxPetsAllowed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblErrorAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancel)
                    .addComponent(jbtnSave)
                    .addComponent(jbtnChangeRestaurant))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        TableModelDiningTables model = (TableModelDiningTables) jTableDiningTables.getModel();
        try {
            this.validation(this.fieldLabelPairs);
            
            if (mode == FormMode.UPDATE) {
                model.updateRestaurant(jtxtAdress.getText().trim(), jcboxNonSmoking.isSelected(), jcboxPetsAllowed.isSelected(), jcboxCuisine.getSelectedItem().toString());
            } else if (mode == FormMode.ADD) {
                model.setRestaurant(jtxtName.getText().trim(), jtxtTIN.getText().trim(), jtxtAdress.getText().trim(), jcboxNonSmoking.isSelected(), jcboxPetsAllowed.isSelected(), jcboxCuisine.getSelectedItem().toString());
            }
            
            controller.saveRestaurant(model.getRestaurant());
            JOptionPane.showMessageDialog(this, "Uspesno sacuvan restoran", "Dodavanje restorana", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Greska pri cuvanju restorana", JOptionPane.ERROR_MESSAGE);
        }
        resetForm();
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnChangeRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangeRestaurantActionPerformed
        setFormMode(FormMode.UPDATE);
    }//GEN-LAST:event_jbtnChangeRestaurantActionPerformed

    private void jbtnUpdateDinningTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateDinningTableActionPerformed
        int rowSelected = jTableDiningTables.getSelectedRow();
        if (rowSelected == -1) {
            return;
        }
        TableModelDiningTables model = (TableModelDiningTables) jTableDiningTables.getModel();
        DiningTable table = model.getDiningTable(rowSelected);
        GUICoordinator.getInstance().changeTable(table);
        model.fireTableDataChanged();
    }//GEN-LAST:event_jbtnUpdateDinningTableActionPerformed

    private void jbtnRemoveDiningTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveDiningTableActionPerformed
        int rowSelected = jTableDiningTables.getSelectedRow();
        if (rowSelected == -1) {
            return;
        }
        TableModelDiningTables model = (TableModelDiningTables) jTableDiningTables.getModel();
//        if (mode == FormMode.ADD) {
//            model.removeDiningTable(rowSelected);
//        } else if (mode == FormMode.UPDATE) {
//            model.markDiningTableAsRemoved(rowSelected);
//        }
    }//GEN-LAST:event_jbtnRemoveDiningTableActionPerformed

    private void jbtnAddDiningTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddDiningTableActionPerformed
        TableModelDiningTables model = (TableModelDiningTables) jTableDiningTables.getModel();
        try {
            String label = jtxtTableLabel.getText();
            int numberOfTables = validateInt(new FieldLabelPair(jtxtNumberOfPeople, jlblErrorNumOfPeople, "broj osoba"));
            String position = jcboxPosition.getSelectedItem().toString();
            model.addDiningTable(label, numberOfTables, position);
            jtxtNumberOfPeople.setText("");
            jcboxPosition.setSelectedIndex(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnAddDiningTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDiningTables;
    private javax.swing.JButton jbtnAddDiningTable;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnChangeRestaurant;
    private javax.swing.JButton jbtnRemoveDiningTable;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnUpdateDinningTable;
    private javax.swing.JComboBox<String> jcboxCuisine;
    private javax.swing.JCheckBox jcboxNonSmoking;
    private javax.swing.JCheckBox jcboxPetsAllowed;
    private javax.swing.JComboBox<String> jcboxPosition;
    private javax.swing.JLabel jlblErrorAdress;
    private javax.swing.JLabel jlblErrorName;
    private javax.swing.JLabel jlblErrorNumOfPeople;
    private javax.swing.JLabel jlblErrorTIN;
    private javax.swing.JLabel jlblErrorTableLabel;
    private javax.swing.JTextField jtxtAdress;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtNumberOfPeople;
    private javax.swing.JTextField jtxtTIN;
    private javax.swing.JTextField jtxtTableLabel;
    // End of variables declaration//GEN-END:variables

    private void prepareForm(FormMode mode) {
        loadCuisines();
        loadPositions();
        prepareDiningTablesTable();
        setFormMode(mode);
    }

    private void loadCuisines() {
        ComboBoxModel model = new DefaultComboBoxModel(Cuisine.values());
        this.jcboxCuisine.setModel(model);
    }

    private void prepareDiningTablesTable() {
        Restaurant restaurant = new Restaurant();
        jTableDiningTables.setModel(new TableModelDiningTables(restaurant));
    }

    private void loadPositions() {
        ComboBoxModel model = new DefaultComboBoxModel(TablePosition.values());
        this.jcboxPosition.setModel(model);
    }

    private void initializeFieldLabelPairs() {
        fieldLabelPairs = new LinkedList() {
            {
                add(new FieldLabelPair(jtxtName, jlblErrorName, "naziv"));
                add(new FieldLabelPair(jtxtTIN, jlblErrorTIN, "PIB"));
                add(new FieldLabelPair(jtxtAdress, jlblErrorAdress, "adresa"));
            }
        };
    }

    private void validation(List<FieldLabelPair> fieldLabelPairs) throws ValidationException {
        for (FieldLabelPair fieldLabelPair : fieldLabelPairs) {
            fieldLabelPair.getLabel().setText("");
            if (fieldLabelPair.getField().getText().isEmpty()) {
                fieldLabelPair.getLabel().setText("Morate uneti " + fieldLabelPair.getFieldName());
            }
        }
        if (fieldLabelPairs.stream().anyMatch(pair -> pair.getField().getText().isEmpty())) {
            throw new ValidationException("Polje ne sme biti prazno");
        }
    }

    private int validateInt(FieldLabelPair pair) throws Exception {
        pair.getLabel().setText("");
        try {
            int numberOfPeople = Integer.parseInt(pair.getField().getText().trim());
            return numberOfPeople;
        } catch (NumberFormatException ex) {
            pair.getLabel().setText("Morate uneti cifru");
            throw new Exception("Neispravan unos");
        }
    }

    private void resetForm() {
        jtxtName.setText("");
        jtxtTIN.setText("");
        jtxtAdress.setText("");
        jtxtNumberOfPeople.setText("");
        jcboxCuisine.setSelectedIndex(0);
        jcboxPosition.setSelectedIndex(0);
        jcboxNonSmoking.setSelected(false);
        jcboxPetsAllowed.setSelected(false);
        prepareDiningTablesTable();
    }

    private void setFormMode(FormMode mode) {
        this.mode = mode;
        switch (mode) {
            case ADD:
                jtxtName.setEnabled(true);
                jtxtAdress.setEnabled(true);
                jtxtTIN.setEnabled(true);
                jtxtNumberOfPeople.setEnabled(true);
                jcboxCuisine.setEnabled(true);
                jcboxPosition.setEnabled(true);
                jcboxNonSmoking.setEnabled(true);
                jcboxPetsAllowed.setEnabled(true);
                jbtnSave.setVisible(true);
                jbtnAddDiningTable.setVisible(true);
                jbtnRemoveDiningTable.setVisible(true);
                jbtnChangeRestaurant.setVisible(false);
                jbtnUpdateDinningTable.setVisible(false);
                break;
            case VIEW:
                jtxtName.setEnabled(false);
                jtxtAdress.setEnabled(false);
                jtxtTIN.setEnabled(false);
                jtxtNumberOfPeople.setEnabled(false);
                jcboxCuisine.setEnabled(false);
                jcboxPosition.setEnabled(false);
                jcboxNonSmoking.setEnabled(false);
                jcboxPetsAllowed.setEnabled(false);
                jbtnSave.setVisible(false);
                jbtnAddDiningTable.setVisible(false);
                jbtnRemoveDiningTable.setVisible(false);
                jbtnChangeRestaurant.setVisible(true);
                jbtnUpdateDinningTable.setVisible(false);
                break;
            case UPDATE:
                jtxtName.setEnabled(false);
                jtxtAdress.setEnabled(true);
                jtxtTIN.setEnabled(false);
                jtxtNumberOfPeople.setEnabled(true);
                jcboxCuisine.setEnabled(true);
                jcboxPosition.setEnabled(true);
                jcboxNonSmoking.setEnabled(true);
                jcboxPetsAllowed.setEnabled(true);
                jbtnSave.setVisible(true);
                jbtnAddDiningTable.setVisible(true);
                jbtnRemoveDiningTable.setVisible(true);
                jbtnChangeRestaurant.setVisible(false);
                jbtnUpdateDinningTable.setVisible(true);
            default:;
        }
    }

    public void showRestaurant(Restaurant restaurant) {
        jtxtName.setText(restaurant.getName());
        jtxtAdress.setText(restaurant.getAdress());
        jtxtTIN.setText(restaurant.getTaxIdNumber());
        jtxtNumberOfPeople.setText("");
        jcboxCuisine.setSelectedItem(Cuisine.valueOf(restaurant.getCuisine()));
        jcboxNonSmoking.setSelected(restaurant.isNonSmoking());
        jcboxPetsAllowed.setSelected(restaurant.isPetsAllowed());
        jTableDiningTables.setModel(new TableModelDiningTables(restaurant));
    }

}
