/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.panel;

import util.Cuisine;
import domain.Restaurant;
import exception.CommunicationException;
import java.awt.BorderLayout;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import ui.controller.ControllerPanelRestaurantsSearch;
import ui.coordinator.GUICoordinator;
import ui.view.components.TableModelRestaurants;
import util.FormMode;

/**
 *
 * @author jeca
 */
public class JPanelRestaurantSearch extends javax.swing.JPanel {

    private ControllerPanelRestaurantsSearch controller;
    private JPanelRestaurantSearch selfReference;
    /**
     * Creates new form JPanelRestaurantSearch
     */
    public JPanelRestaurantSearch(boolean justPreview) {
        controller = ControllerPanelRestaurantsSearch.getInstance();
        selfReference = this;
        initComponents();
        prepareForm(justPreview);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableRestaurants = new javax.swing.JTable();
        jbtnShowRestaurant = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga restorana"));

        jtxtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtNameKeyReleased(evt);
            }
        });

        jLabel8.setText("Naziv restorana:");

        jtableRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtableRestaurants);

        jbtnShowRestaurant.setText("PrikaziRestoran");
        jbtnShowRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowRestaurantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 419, Short.MAX_VALUE)
                        .addComponent(jbtnShowRestaurant)))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnShowRestaurant)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNameKeyReleased
        showRestaurants(filterRestaurantsByName());
    }//GEN-LAST:event_jtxtNameKeyReleased

    private void jbtnShowRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowRestaurantActionPerformed
        int indexSelected = jtableRestaurants.getSelectedRow();
        if (indexSelected != -1) {
            Restaurant restaurant = ((TableModelRestaurants)jtableRestaurants.getModel()).getRestaurant(indexSelected);
            GUICoordinator.getInstance().showRestaurant(restaurant);
        }
    }//GEN-LAST:event_jbtnShowRestaurantActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnShowRestaurant;
    private javax.swing.JTable jtableRestaurants;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables

    private void prepareForm(boolean justPreview) {
        if(justPreview){
            jbtnShowRestaurant.setVisible(false);
        }
        prepareRestaurantsTable();
    }

    private void prepareRestaurantsTable() {
        List<Restaurant> restaurants = controller.getAllRestaurants();
        TableModelRestaurants model = new TableModelRestaurants(restaurants);
        jtableRestaurants.setModel(model);
    }

    public void showRestaurants(List<Restaurant> restaurants) {
        TableModelRestaurants model = (TableModelRestaurants) jtableRestaurants.getModel();
        model.setRestaurants(restaurants);
    }

    private List<Restaurant> filterRestaurantsByName() {
        String nameTyped = jtxtName.getText();
        return controller.filterByName(nameTyped);
    }
}
